title: Code Outside the Box
description: This is my blog! Let's learn coding together!
baseurl: ""
url: "https://microchip818.github.io"
theme: null
markdown: kramdown
author: Ethan
plugins:
  - jekyll-last-modified-at
  
timezone: America/Los_Angeles
